// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ywveglyrzyuaqebuitso.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3dmVnbHlyenl1YXFlYnVpdHNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNTQyNDQsImV4cCI6MjA2NTgzMDI0NH0.c4partMYMALnDsgsVSwEqqN4OPUJDIe3Y5d857CsrRM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);